-- Model Lab — consolidated model database
-- Schema for SQLite-backed model explorer
-- JSON generated by model-lab-export.py, consumed by Vue 3 at /tools/model-lab.html

CREATE TABLE IF NOT EXISTS models (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    slug        TEXT UNIQUE NOT NULL,           -- url-safe identifier
    name        TEXT NOT NULL,                  -- display name
    org         TEXT NOT NULL,                  -- organisation
    release_date TEXT,                          -- ISO date or quarter
    params_total TEXT,                          -- e.g. '2.8T', '975B'
    params_active TEXT,                         -- e.g. '41B', '—'
    context_window INTEGER,                     -- in tokens
    architecture TEXT,                          -- 'MoE', 'Dense', 'MoE+Hybrid'
    num_experts INTEGER,                        -- for MoE models
    experts_per_token INTEGER,                  -- active experts per token
    training_data_cutoff TEXT,
    pricing_input  REAL,                        -- per 1M tokens (USD)
    pricing_output REAL,                        -- per 1M tokens (USD)
    license       TEXT,                         -- e.g. 'MIT', 'Proprietary', 'OpenRAIL-M'
    notes         TEXT,                         -- free-text notes
    created_at    TEXT DEFAULT (datetime('now')),
    updated_at    TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS benchmarks (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    model_id    INTEGER NOT NULL REFERENCES models(id) ON DELETE CASCADE,
    category    TEXT NOT NULL,                  -- 'coding', 'reasoning', 'agentic', 'vision', 'multilingual', 'math', 'general'
    benchmark   TEXT NOT NULL,                  -- e.g. 'LiveCodeBench', 'MATH-500', 'MMLU-Pro'
    score       REAL,                          -- the metric value
    metric      TEXT DEFAULT 'score',           -- e.g. 'pass@1', 'accuracy', 'elapsed_ms'
    source      TEXT,                           -- where this score came from
    UNIQUE(model_id, benchmark, metric)
);

CREATE TABLE IF NOT EXISTS tags (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    name        TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS model_tags (
    model_id    INTEGER NOT NULL REFERENCES models(id) ON DELETE CASCADE,
    tag_id      INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (model_id, tag_id)
);

-- View for JSON export: models with their benchmark scores as a JSON array
CREATE VIEW IF NOT EXISTS v_model_export AS
SELECT
    m.id,
    m.slug,
    m.name,
    m.org,
    m.release_date,
    m.params_total,
    m.params_active,
    m.context_window,
    m.architecture,
    m.num_experts,
    m.experts_per_token,
    m.training_data_cutoff,
    m.pricing_input,
    m.pricing_output,
    m.license,
    m.notes,
    COALESCE(
        json_group_array(
            json_object(
                'category', b.category,
                'benchmark', b.benchmark,
                'score', b.score,
                'metric', b.metric,
                'source', b.source
            )
        ) FILTER (WHERE b.id IS NOT NULL),
        '[]'
    ) AS benchmarks
FROM models m
LEFT JOIN benchmarks b ON b.model_id = m.id
GROUP BY m.id
ORDER BY m.release_date DESC;
